### ISSUE TITLE
Package issue on solidity test

### ISSUE THREAD

**Issue by thomas-nguy** [PeggyJV/gravity-bridge#354]
Trying to run `yarn test` on the solidity folder, I come up with an error

```

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /xxx/go/src/github.com/PeggyJV/gravity-bridge/solidity/node_modules/uuid/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/thomasnguy/Documents/go/src/github.com/PeggyJV/gravity-bridge/solidity/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/xxx/go/src/github.com/PeggyJV/gravity-bridge/solidity/node_modules/request/lib/auth.js:4:12) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
````

node version `v14.16.0`

downgrading uuid to 7.0.3 seems to fix this error

**Comment by thomas-nguy** [comment]
Probably causes by typechain using a lower version dependencies

https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#800-2020-04-29

**Comment by EricBolten** [comment]
Closing this issue as the PR was merged.
